#!/usr/bin/env bash

echo '#!/usr/bin/env python3'>$1

echo '
import sys, MySQLdb

db = MySQLdb.connect(host="localhost", user=sys.argv[1], passwd=sys.argv[2]
	db=sys.argv[3], port=3306)
cur = db.cursor()
cur.execute("")
rows = cur.fetchall()
for row in rows:
    print(row)
cur.close()
db.close()
'>>$1

chmod u+x $1
